function [Ln,DLnDx,D2LnDx2]=f_EvalLaguerrePolynomials(vn,u)
%
% function [Ln,DLnDx,D2LnDx2]=f_EvalLaguerrePolynomials(vn,u)
% 
% This function generates the Laguerre polynomials of order vn in the
% points x; the outputs are matrices of dimension length(vn) x length(x). 
%
% The polynomials and their first derivative are generated by means of
% recurrence relationships; then, the Legendre equation is used to find the
% second derivative as a function of the previous terms.
%
% Alberto Tibaldi, Ver. 1.0 21/07/2014
%                  Ver. 1.1 09/02/2016
%

Ln=zeros(length(vn),length(u));
DLnDx=zeros(length(vn),length(u));

Ln(1,:)=ones(size(u));
Ln(2,:)=1-u;

for indn=2:(length(vn)-1)
    Ln(indn+1,:)=((2*vn(indn)+1-u).*Ln(indn,:)-vn(indn)*Ln(indn-1,:))/(vn(indn)+1);
end

DLnDx(2,:)=-1;

for indn=3:length(vn)
    DLnDx(indn,:)=DLnDx(indn-1,:)-Ln(indn-1,:);
end

X=ones(length(vn),1)*u;
VN=vn.'*ones(size(u));
D2LnDx2=-((1-X).*DLnDx+VN.*Ln)./(X);

return